// for letter grid
export const SET_NUM_LETTERS = "SET_NUM_LETTERS";
export const TRIGGER_LETTER_INPUT = "TRIGGER_LETTER_INPUT";
export const TRIGGER_BACKSPACE = "TRIGGER_BACKSPACE";
export const SET_ALERT = "SET_ALERT";
export const SET_ANSWER = "SET_ANSWER";
export const SET_GUESS_FEEDBACK = "SET_GUESS_FEEDBACK";
export const SET_WORD_LIST = "SET_WORD_LIST";

// for game statistics
export const SET_POSSIBLE_GUESSES = "SET_POSSIBLE_GUESSES";
export const START_LOADING_GUESSES = "START_LOADING_GUESSES";
export const STOP_LOADING_GUESSES = "STOP_LOADING_GUESSES";