export const SET_NUM_LETTERS = "SET_NUM_LETTERS";
export const SET_CELL_LETTER = "SET_CELL_LETTER";
export const TRIGGER_LETTER_INPUT = "TRIGGER_LETTER_INPUT";
export const TRIGGER_KEY_ENTER = "TRIGGER_KEY_ENTER";
export const INCREMENT_ACTIVE_CELL = "INCREMENT_ACTIVE_CELL";